Gated content and Braze soft-login support
parameter1/science-medicine-group-websites pull request #139
Opened 2022-12-06 19:13 UTC by solocommand

Requires parameter1/identity-x#24

- Adds content gating middleware to read the `__idx_gating` cookie to read previously computed identity state.
- Adds braze identity middleware to set the `__idx_gating` cookie (currently with 7d duration)
  - Enabled on the content route for each site
  - Unify newsletterState/formatting in site content routes

2022-12-06 21:01 UTC, zarathustra323 approved these changes

2022-12-06 21:02 UTC, zarathustra323 requested changes
LOL didn't mean it

2022-12-07 13:48 UTC, brandonbk approved these changes

2022-12-07 14:01 UTC, zarathustra323 requested changes

2022-12-07 14:01 UTC, zarathustra323 commented on packages/braze/middleware/set-identity-cookie.js
> +  if (!brazeExtId || !/^[a-z0-f]{24}$/g.test(brazeExtId)) return next();
This should use the i flag, not g

2022-12-07 15:40 UTC, merged