Add 2023 to page-detail for RSNA
parameter1/science-medicine-group-websites pull request #463
Opened 2023-11-08 23:17 UTC by jwade1327

This will allow the ‘previous coverage’ block to appear
<img width="801" alt="Screen Shot 2023-11-08 at 5 15 21 PM" src="https://github.com/parameter1/science-medicine-group-websites/assets/64623209/97ad48f2-4d03-44e9-b848-63aa627f5c93">

2023-11-08 23:17 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Adjust routing for RSNA sections](https://trello.com/c/485Yv7gK/455-adjust-routing-for-rsna-sections)

2023-11-09 15:22 UTC, Shinsina requested changes

2023-11-09 15:22 UTC, Shinsina commented on sites/auntminnie.com/config/page-details.js
> +    siblinRoutes: rsnaSiblingRoutes,
Can we correct this to be `siblingRoutes`? I think this is also in the `conferences-with-pinned.marko` file spelled incorrectly so it will need to be corrected there as well.

2023-11-09 16:45 UTC, Shinsina approved these changes

2023-11-09 16:45 UTC, merged