Create ECR conference page & update landing page
parameter1/science-medicine-group-websites pull request #519
Opened 2024-02-13 17:42 UTC by jwade1327

<img width="1792" alt="Screen Shot 2024-02-13 at 11 39 55 AM" src="https://github.com/parameter1/science-medicine-group-websites/assets/64623209/2a46bd18-8a17-4f54-b2e6-4820d5c7ea88">

<img width="1791" alt="Screen Shot 2024-02-13 at 11 39 39 AM" src="https://github.com/parameter1/science-medicine-group-websites/assets/64623209/8d75d6a9-7e30-40e7-adbb-5d2d4205a462">

2024-02-13 17:43 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup ECR section - AMEU](https://trello.com/c/fMkIs6Xd/531-setup-ecr-section-ameu)

2024-02-13 18:10 UTC, Shinsina requested changes
I'm also assuming that the templates like `conference-with-pinned` were copy pasted from AuntMinnie, if that's the case they should likely be moved up to the global/shared package and imported accordingly, assuming there is no differences between each site.

2024-02-13 18:10 UTC, Shinsina commented on sites/auntminnieeurope.com/server/routes/conference.js
> +  '2018',
![image](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/9855f701-ed39-4775-a51d-4e000d2b922c)


These don't exist, are they suppose to?

2024-02-13 20:59 UTC, Shinsina requested changes

2024-02-13 20:59 UTC, Shinsina commented on sites/auntminnieeurope.com/config/page-details.js
> +  { title: 2018, href: 'resources/conferences/ecr/2018', alt: '2018 European Congress of Radiology (ECR) News Coverage' },
These likewise should be corrected with the sections that actually exist (this goes for the entire file)

2024-02-14 21:15 UTC, Shinsina approved these changes

2024-02-14 21:15 UTC, merged