Identity-X GET and DELETE endpoints
parameter1/science-medicine-group-websites pull request #526
Opened 2024-02-21 19:21 UTC by Shinsina

**REQUIRES: https://github.com/parameter1/base-cms/pull/878**

![Screenshot from 2024-02-20 15-42-27](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/252f17a2-9966-44c3-9c17-679610a656be)
![Screenshot from 2024-02-20 15-39-35](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/df94639c-4a4d-48f0-905e-48e117f1681a)
![Screenshot from 2024-02-20 15-40-07](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/7c41b20e-4901-4e28-84e3-76be3ec1c17c)
![Screenshot from 2024-02-20 15-40-28](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/8ab599f4-7349-45e0-99a7-823b0b0f6a57)
![Screenshot from 2024-02-20 15-40-44](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/c46745a6-2415-4ac8-9eaa-ad160dae1b21)
![Screenshot from 2024-02-20 15-41-59](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/1e128567-5d8f-4c81-8aee-a5f2ecc1a9f1)
![Screenshot from 2024-02-20 15-42-09](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/eeb040b0-ac5b-40aa-94a6-b90a9d094400)

2024-02-22 17:16 UTC, solocommand requested changes
Make sure you return (or otherwise skip) remaining code after sending a response, otherwise the following statements will still be executed, leading to `Cannot send headers...` errors server-side.

Otherwise, looks good! 👍🏾

2024-02-22 17:16 UTC, solocommand commented on packages/braze/ingest/index.js
> +        });
Return after send

2024-02-22 17:16 UTC, solocommand commented on packages/braze/ingest/index.js
> +        });
Return after sending the response

2024-02-22 17:16 UTC, solocommand commented on packages/braze/ingest/index.js
> +        });
return after send

2024-02-29 15:36 UTC, B77Mills approved these changes

2024-02-29 15:36 UTC, merged