Setup ISRMR 2024
parameter1/science-medicine-group-websites pull request #540
Opened 2024-04-22 16:31 UTC by jwade1327

<img width="1792" alt="Screenshot 2024-04-22 at 11 24 11 AM" src="https://github.com/parameter1/science-medicine-group-websites/assets/64623209/4fcd91b3-74a7-4f9c-9df1-3f52989c6015">
<img width="1792" alt="Screenshot 2024-04-22 at 11 30 07 AM" src="https://github.com/parameter1/science-medicine-group-websites/assets/64623209/87813497-4607-4d03-a519-e975b274f7e0">

2024-04-22 16:32 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup ISMRM on AM and AME](https://trello.com/c/dSvYAQUc/555-setup-ismrm-on-am-and-ame)

2024-04-22 18:44 UTC, Shinsina requested changes
It doesn't look like `/resources/conference/ismrm/2024` works on AuntMinnie Europe, it looks like it's supposed to given the changes in this PR.

![image](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/87725eb9-66c6-4bf1-83fd-a15fc4184be6)

2024-04-23 13:16 UTC, Shinsina requested changes

2024-04-23 13:16 UTC, Shinsina commented on sites/auntminnieeurope.com/config/page-details.js
> +    siblingRoutes: ismrmSiblingRoutes,
Do these also need to be corrected to `/resources/conferences`?

2024-04-23 13:16 UTC, Shinsina commented on sites/auntminnieeurope.com/config/page-details.js
> +
Likewise here does this need to be changed to `resources/conferences/ismrm/2024`?

2024-04-23 13:25 UTC, jwade1327 commented on sites/auntminnieeurope.com/config/page-details.js
> +
@Shinsina Apologies!!!

2024-04-23 13:35 UTC, Shinsina approved these changes

2024-04-23 13:36 UTC, merged