Create SNMMI route, page-details, & GAM ad unit
parameter1/science-medicine-group-websites pull request #549
Opened 2024-05-30 18:47 UTC by jwade1327

2024-05-30 18:47 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [SNMMI ad units for AM/AME](https://trello.com/c/NZvMCokr/571-snmmi-ad-units-for-am-ame)

2024-06-03 20:07 UTC, Shinsina requested changes

2024-06-03 20:07 UTC, Shinsina commented on sites/auntminnie.com/server/routes/conference.js
> +    app.get(`/:aliases(resources/conference/snmmi/${year})`, withWebsiteSection({
This is likely causing your error as the `withWebsiteSection` middleware is looking for either an `aliasResolver` function or `req.params.alias` which this doesn't not include this would be including `req.params.aliases` :)

2024-06-03 20:07 UTC, Shinsina commented on sites/auntminnieeurope.com/server/routes/conference.js
> +    app.get(`/:aliases(resources/conferences/snmmi/${year})`, withWebsiteSection({
Same thing as the other comment :)

2024-06-04 13:45 UTC, merged