Set `__p1e_idt` based in incoming cookie value
parameter1/science-medicine-group-websites pull request #567
Opened 2024-06-19 17:45 UTC by Shinsina

The incoming value for `__idx_idt` is set here https://github.com/parameter1/science-medicine-group-websites/blob/master/packages/braze/middleware/set-idx-cookie.js utilizing `braze_ext_id` which the cookie value is set via https://github.com/parameter1/science-medicine-group-websites/blob/master/packages/braze/middleware/set-id-cookies.js so ultimately if `braze_ext_id` is set on the query string the `__p1e_idt` value will be set accordingly.

Example utilizing http://www-smg-ame.dev.parameter1.com:9955/clinical-news/mri/article/15662044/irish-radiologist-returns-to-work-after-3week-suspension?lid=wk8n4sqxtvqy&braze_int_id=64511eb0ca51d90001ab524b&braze_ext_id=64511eaa2ed1af7082a21b98 for the URL:
![Screenshot from 2024-06-19 12-42-24](https://github.com/parameter1/science-medicine-group-websites/assets/46794001/2ff10902-0bba-4aaa-aacf-33cd903d2828)

2024-06-19 17:47 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Braze Sessions Not Recorded](https://trello.com/c/xqrIatG3/495-braze-sessions-not-recorded)

2024-06-19 18:36 UTC, solocommand requested changes
Update to use P1E's Identity module [query builder](https://github.com/parameter1/events-lib/blob/main/src/app/identity.js#L67)

2024-06-19 18:36 UTC, solocommand commented on packages/global/components/document.marko
> +      </if>
```suggestion
        identity-query-builder=createIdentityBuilder(context, identityX.getIdentity(res))        
        enable-gam-plugin=true
      />
```

Update the query builder utility to use the passed identity instead of bailing, if there's no active user in the context.

2024-06-19 19:56 UTC, solocommand approved these changes

2024-06-20 14:36 UTC, Shinsina commented
Setting to draft as this is pending further investigation.

2024-10-12 18:45 UTC, merged