Confirm user via incoming `braze_ext_id` on query string if not Identity-X verified
parameter1/science-medicine-group-websites pull request #596
Opened 2024-07-17 17:49 UTC by Shinsina

2024-07-17 17:49 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Confirming Email Addresses](https://trello.com/c/OaNDn7T2/561-confirming-email-addresses)

2024-07-26 13:56 UTC, B77Mills requested changes

2024-07-26 13:56 UTC, B77Mills commented on packages/braze/middleware/confirm-user-via-query-string.js
> +  if (!identity || identity.verified) return next(); // invalid or deleted user, don't confirm user
@Shinsina Can thin all just be a one line and a return of next?

if(identity && !identity.verified) await braze.confirmUser(identity.email, identity.id, 'identity-x');

return next();

}

2024-07-26 14:06 UTC, B77Mills approved these changes

2024-07-26 14:07 UTC, merged