Add reCAPTCHA v3 to Braze Preference Center form submission.
parameter1/science-medicine-group-websites pull request #82
Opened 2022-10-05 16:05 UTC by Shinsina

Mostly copied logic from https://github.com/parameter1/base-cms/blob/master/packages/marko-web-contact-us/browser/form.vue was able to confirm it will fail (forgot to include our domain (parameter1.com which is used for the development instance) on the acceptable domain list initially)

![WORKS](https://user-images.githubusercontent.com/46794001/194108326-d5df1457-33ba-48f8-9b98-f44acd5e8464.png)

2022-10-05 16:06 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add reCAPTCHA v3 to Braze preference center feature](https://trello.com/c/cgGnRbda/82-add-recaptcha-v3-to-braze-preference-center-feature)

2022-10-06 17:31 UTC, solocommand requested changes

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +      const token = await recaptchaGetToken({ siteKey: this.siteKey, action: 'brazerPreferenceCenter' });
This should be `brazePreferenceCenter` not `brazerPreferenceCenter`

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +      if (token) {
Don't wrap all of this in an if check. Instead, put your recaptcha call inside the try, and throw if there is no token. The reset of the error message is fine to keep.

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +    },
No need for separate and error/loading states here. 
```suggestion
    async loadRecaptcha() {
      try {
        this.loading = true;
        await recaptchaLoad({ siteKey: this.siteKey });
      } catch (e) {
        this.error = e.message;
      } finally {
        this.loading = false;
      }
    },
```

2022-10-06 17:31 UTC, solocommand commented on packages/global/routes/braze.js
> +      await validateToken({ token, secretKey: RECAPTCHA_V3_SECRET_KEY, actions: ['brazerPreferenceCenter'] });
Rename action key

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +    recaptcha: { loading: false, error: null },
remove

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +      </p>
Remove

2022-10-06 17:31 UTC, solocommand commented on packages/global/browser/braze-preference-center.vue
> +      >
Revert

2022-10-06 18:15 UTC, solocommand approved these changes

2022-10-06 18:18 UTC, merged